### ISSUE TITLE
Convert Date, Time and Timestamp values for exported data (downloads)

### ISSUE THREAD

**Issue by bittner** [xresch/EngineeredMonitoringPlatform#11]
The table widget now allows to download data being displayed as CSV, JSON or XML. This is great! 

## Date, Time, Timestamp in Epoch time

When that data contains date, time or timestamp values, the values are exported as they are managed by EMP, in epoch time. Unfortunately, this is not particularly suitable for at least Microsoft Excel and LibreOffice Calc, which cannot easily convert or display epoch time values. See, e.g.

- [Convert Epoch Time to Date in Excel (2 Easy Methods)](https://www.exceldemy.com/convert-epoch-time-to-date-excel/) (ExcelDemy)
- [How do I convert a Unix epoch timestamp into a human readable date/time in Excel?](https://stackoverflow.com/questions/15164237/how-do-i-convert-a-unix-epoch-timestamp-into-a-human-readable-date-time-in-excel) (StackOverflow)
- [How do I convert a UNIX timestamp to libreoffice date time?](https://ask.libreoffice.org/t/how-do-i-convert-a-unix-timestamp-to-libreoffice-date-time/102300) (Ask.LibreOffice.org)

## Export date and time values as displayed

To solve this issue, date, time and timestamp values would need to be exported roughly as they are displayed. It might make sense to convert those values from epoch time to [ISO 8601 date and time format](https://www.iso.org/iso-8601-date-and-time-format.html) for the exports.

## Related Issues

- #6

**Comment by xresch** [comment]
Hi @bittner,

the format with formatfield-command  is only applied to the UI rendering in the browser and not to the raw data.
This cannot be done for CSV exports, as this would lead to a lot of other issues.

What you can do instead is using the function timeformat, what will format the milliseconds into a string already on server side.
Therefore the data is already formatted when received from server side and you will also be formatted in the exported CSV.

![image](https://github.com/user-attachments/assets/13e5c523-0645-44fc-95e7-0b5d024030a7)

**Comment by bittner** [comment]
This works out, thank you! :1st_place_medal:
