### ISSUE TITLE
Download button on CSV Table widget

### ISSUE THREAD

**Issue by bittner** [xresch/EngineeredMonitoringPlatform#6]
The CSV Table widget has the ability to let the user switch the display to "CSV". In theory, users could hence:

1. switch Display As to "CSV"
2. set the Page Size to the maximum
3. select the displayed data (e.g. using the mouse)
4. copy+paste it into a text editor or spreadsheet application (e.g. LibreOffice Calc, Microsoft Excel)

## Usability Feedback

We've had feedback from our principal users (clients) that they'd like a <kbd>Download</kbd> button instead, which would directly trigger an actual download.

**Comment by xresch** [comment]
Hi @bittner,

download option has been added to the query command "display", which allows to display a download button:
https://github.com/xresch/CoreFramework/commit/3dced43e398c5ac208cd6e99b98cf05fe83e79c5

![image](https://github.com/user-attachments/assets/517e5f40-3b38-4ca3-a412-cb008e7277f0)

Will be available in the next release.

Cheers
Reto

**Comment by xresch** [comment]
ticket closed as resolved

**Comment by xresch** [comment]
ticket closed as resolved
