### ISSUE TITLE
Get dashboard ID as parameter value

### ISSUE THREAD

**Issue by bittner** [xresch/EngineeredMonitoringPlatform#8]
We have a dashboard widget with a list of values that links to the dashboard itself (with additional query parameters) for further drill-down using a `| formatlink` filter. For this, we obviously need the dashboard ID in the generated URL, e.g. `?id=12345`.

As we use this value on several places and the dashboard also gets duplicated from time to time, it would makes sense to have the ID value calculated dynamically. Apparently, this value is not available as a parameter yet, e.g.

```shell
| formatlink
    newtab=false
    CODE = "?id=" + param("id")
```

The above code doesn't work. The `param("id")` call always returns `0`.

Is there some other way to derive the ID of the current dashboard? If not, could this feature be added?

**Comment by xresch** [comment]
Hi @bittner,

there is the parameter "Dashboard ID" which you can use to get the ID:
![image](https://github.com/user-attachments/assets/a01c5656-af7c-467f-a9bb-ab67ddad7449)

**Comment by bittner** [comment]
Great! That worked. :heavy_check_mark:
