### ISSUE TITLE
No data from Dynatrace Host Metrics widgets for JBoss

### ISSUE THREAD

**Issue by iSimsi** [xresch/EngineeredMonitoringPlatform#9]
No data is being returned from the"Dynatrace" ->  "Host Metric Chart" & "Host Metrics Status" widgets when using the metrics "builtin:tech.jboss.connectionPool.AvailebleCount". Die data is available in Dynatrace.

**Comment by xresch** [comment]
Ciao Simon,

This probably won't work as Host Metric Chart only works with host metrics, not with any metrics.
Another issue with that is the return format of the metrics API is not strictly defined.
I assume above metric is of type "SERVICE" or "SERVICE_INSTANCE" or similar.

However, you can use the query language to fetch the data directly from the Dynatrace API.
You find examples in the manual:
https://github.com/xresch/EngineeredMonitoringPlatform/blob/master/EngineeredMonitoringPlatform/src/main/java/com/xresch/emp/features/dynatrace/manual/manual_dynatrace_queries.html

I assume you would have to do something like this(untested code):
```bash
| paramdefaults
	metric = "builtin:tech.jboss.connectionPool.AvailableCount" 
	resolution = 2
| source web 
	each =  [
		 "your service name"
		,"another service name"
	]
	url = ( 
			credentials("DYN_API_PROD").url 
			+ "/v2/metrics/query"
			+ "?metricSelector="+param(metric)
			+ "&resolution="+param(resolution)
			+ "&entitySelector=type(SERVICE),entityName.in("+meta('each')+")"
			+ "&from="+timeoffset(latest(), -5, 'm' )
			+ "&to="+latest()
		)
	headers=object( "Authorization" "Api-Token "+ credentials("DYN_API_PROD").password )
| unbox result
| unbox result.data
# extract your metrics and do charting 
# | chart ...
```

**Comment by iSimsi** [comment]
Thanks for your suggestions.

**Comment by xresch** [comment]
you are welcome
